# Generated by Django 3.0.3 on 2020-03-06 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200306_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=300)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user_pk_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user_pk_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.DeleteModel(
            name='Introduce',
        ),
    ]
