# Generated by Django 3.0.3 on 2020-03-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200306_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_pk_id',
            new_name='user_pk',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='user_pk_id',
            new_name='user_pk',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_pk_id',
            new_name='user_pk',
        ),
    ]
