# Generated by Django 3.0.3 on 2020-03-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200306_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='user_id',
        ),
    ]
